### ISSUE TITLE
abs macro in Arduino.h collides with abs() function in cstdlib header

### ISSUE THREAD

**Issue by jorenheit** [maniacbug/StandardCplusplus#10]
I got compilation errors due to a macro (abs) defined in Arduino.h. Encapsulating the inline definition of the abs() function in the cstdlib header, in #ifndef ... #endif directives fixed this issue. I hope I didn't break anything else in the meantime...

**Comment by webelcomau** [comment]
similar problem, had to switch to explicit fabs(float) when using StandardCplusplus, abs() started giving 0.

**Comment by Bravo555** [comment]
Same problem here.

**Comment by maniacbug** [comment]
Fixed in #34
