### ISSUE TITLE
expected unqualified-id before 'long'

### ISSUE THREAD

**Issue by jefferai** [maniacbug/StandardCplusplus#2]
I'm trying to use this library and hitting a problem. Below is the (verbose) output. I did notice that the StandardCplusplus.h include does an #undef abs, which I'm assuming is related to this, but including that file or not made no difference in my project. Any ideas?...thanks in advance.

[ 68%] Building CXX object CMakeFiles/hub.dir/src/main.cpp.obj
/home/jmitchell/Arduino/avr8-gnu-toolchain-linux_x86_64/bin/avr-g++   -DUBRRH -DUBRR0H -DUBRR1H -DUBRR2H -DUBRR3H -DDEBUG_K=1 -g -Os       -mcall-prologues -ffunction-sections -fdata-sections -fno-exceptions -I/home/jmitchell/Arduino/libraries/Arduino-Style/StandardCplusplus -I/home/jmitchell/Arduino/libraries/messaging -I/home/jmitchell/Arduino/arduino-1.0.1/libraries -I/home/jmitchell/Arduino/arduino-1.0.1/hardware/arduino/variants/mega    -DF_CPU=16000000L -DARDUINO=100 -mmcu=atmega2560 -I/home/jmitchell/Arduino/arduino-1.0.1/hardware/arduino/cores/arduino -I/home/jmitchell/Arduino/arduino-1.0.1/libraries -I/home/jmitchell/Arduino/arduino-1.0.1/hardware/arduino/variants/mega  -I/home/jmitchell/Arduino/libraries/Arduino-Style/SoftwareSerial -I/home/jmitchell/Arduino/arduino-1.0.1/libraries/Wire -I/home/jmitchell/Arduino/libraries/Arduino-Style/Usb -I/home/jmitchell/Arduino/libraries/Arduino-Style/AndroidAccessory -I/home/jmitchell/Arduino/libraries/Arduino-Style/DebugPrint -I/home/jmitchell/Arduino/libraries/Arduino-Style/Time -o CMakeFiles/hub.dir/src/main.cpp.obj -c /home/jmitchell/Arduino/applications/hub/src/main.cpp
In file included from /home/jmitchell/Arduino/libraries/Arduino-Style/StandardCplusplus/memory:22:0,
                 from /home/jmitchell/Arduino/libraries/Arduino-Style/StandardCplusplus/char_traits:22,
                 from /home/jmitchell/Arduino/libraries/Arduino-Style/StandardCplusplus/iosfwd:21,
                 from /home/jmitchell/Arduino/libraries/Arduino-Style/StandardCplusplus/iterator:21,
                 from /home/jmitchell/Arduino/applications/hub/src/main.cpp:32:
/home/jmitchell/Arduino/libraries/Arduino-Style/StandardCplusplus/cstdlib:60:14: error: expected unqualified-id before 'long'
/home/jmitchell/Arduino/libraries/Arduino-Style/StandardCplusplus/cstdlib:60:14: error: expected ')' before 'long'
/home/jmitchell/Arduino/libraries/Arduino-Style/StandardCplusplus/cstdlib:60:14: error: expected ')' before 'long'

**Comment by amotl** [comment]
Hi there,

GH-34 has a fix for this, as suggested by @eric-wieser -- thanks! We are hosting a working version at [^1] on behalf of the `next` branch. Pulling in the `StandardCplusplus` library into a [PlatformIO](https://platformio.org/) configuration like outlined below works for us.

With kind regards,
Andreas.

``ìni
[platformio]
src_dir = .

[env:atmega328p]
platform = atmelavr@^2
board = uno
framework = arduino
lib_deps =
    https://github.com/hiveeyes/StandardCplusplus#next
```

[^1]: https://github.com/hiveeyes/StandardCplusplus

**Comment by maniacbug** [comment]
Merged #34 which fixes this. Thanks!

**Comment by jefferai** [comment]
Wow. Fun to see my bug from 11 years ago get closed! Just a lovely unexpected GitHub notification.
