### ISSUE TITLE
Bitset flip and reset overwrite adjacent memory

### ISSUE THREAD

**Issue by TyberiusPrime** [maniacbug/StandardCplusplus#25]
Both functions go like this
```(size_t i = 0; i <= num_bytes; ++i){```
When the should go with 
```(size_t i = 0; i < num_bytes; ++i){```

i.e. they iterate one element to far in the internal storage.

**Comment by mike-matera** [comment]
Hi. This project is dead. I maintain a replacement: 

https://github.com/mike-matera/ArduinoSTL

You can install it directly from the Arduino Library Manager. This issue is fixed in my copy.
