### ISSUE TITLE
Bugs in complex

### ISSUE THREAD

**Issue by AndreasMartin72** [maniacbug/StandardCplusplus#26]
In line 310: 
		return complex**t**<T>(sinh(v.real()) * cos(v.imag()), cosh(v.real()) * sin(v.imag()) );

In line 302:
		return polar(pow(v,p.real()), **y**.imag() * log(**x**) );

**Comment by mike-matera** [comment]
This project is dead. Do you see the same problem in ArduinoSTL? 

https://github.com/mike-matera/ArduinoSTL

**Comment by AndreasMartin72** [comment]
Yes, as you can see...
