### ISSUE TITLE
enable_if is not defined in type_traits header

### ISSUE THREAD

**Issue by me21** [maniacbug/StandardCplusplus#28]
According to https://en.cppreference.com/w/cpp/types/enable_if it should be in the `type_traits` header file. But currently the lib doesn't mention `enable_if` at all.

The same goes for `is_arithmetic` (https://en.cppreference.com/w/cpp/types/is_arithmetic).

**Comment by maniacbug** [comment]
Yeah, `enable_if` is a C++11 construct. This library predates C++11. Likewise, `enable_if` isn't implemented upstream either.
