### ISSUE TITLE
logic_error

### ISSUE THREAD

**Issue by xavier2910** [maniacbug/StandardCplusplus#30]
When I try to throw a `logic_error`, I am given an error saying: `namespace "std" has no member "logic_error"`. I have included the `stdexcept` header.

**Comment by maniacbug** [comment]
This is because exception handling is disabled by default.

See system_configuration.h:

```c++
#undef __UCLIBCXX_EXCEPTION_SUPPORT__
```

You can `#define` that if you really want to tangle with exceptions. Be careful, though!
