### ISSUE TITLE
Compilation error:

### ISSUE THREAD

**Issue by Timothychen00** [maniacbug/StandardCplusplus#33]
In file included from /Users/timothychen_1/Documents/Arduino/libraries/StandardCplusplus-master/istream:24:0,
                 from /Users/timothychen_1/Documents/Arduino/libraries/StandardCplusplus-master/serstream:19,
                 from /Users/timothychen_1/Documents/Arduino/libraries/StandardCplusplus-master/examples/string_vector/string_vector.ino:2:
/Users/timothychen_1/Documents/Arduino/libraries/StandardCplusplus-master/ostream:318:50: error: default argument for template parameter for class enclosing 'class std::basic_ostream<charT, traits>::sentry'
   class _UCXXEXPORT basic_ostream<charT,traits>::sentry
                                                  ^~~~~~
In file included from /Users/timothychen_1/Documents/Arduino/libraries/StandardCplusplus-master/serstream:19:0,
                 from /Users/timothychen_1/Documents/Arduino/libraries/StandardCplusplus-master/examples/string_vector/string_vector.ino:2:
/Users/timothychen_1/Documents/Arduino/libraries/StandardCplusplus-master/istream:343:107: error: default argument for template parameter for class enclosing 'class std::basic_istream<charT, traits>::sentry'
  template <class charT,class traits = char_traits<charT> > class _UCXXEXPORT basic_istream<charT,traits>::sentry {
                                                                                                           ^~~~~~

exit status 1

Compilation error: exit status 1

**Comment by maniacbug** [comment]
Please try again, since #20 has been merged. If still fails, please provide a small snippet of code which would repro the problem.
