### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by nicolaspanel** [maniacbug/StandardCplusplus#6]
After copying files into the `/Arduino/libraries/StandardCplusplus` folder, IDE returns a compilation error because some operators are defined twice (with Arduino 1.0.4).
The solution I've found to bypass the problem is to delete the following files:
- `StandardCplusplus / new_opv.cpp`
- `StandardCplusplus / del_opv.cpp`

Hope it helps

**Comment by maniacbug** [comment]
Merged #8. Should fix this.
